### ISSUE TITLE
Only 12 Courses Listed

### ISSUE THREAD

**Issue by Purus** [lwille/plugin.video.udemy#4]
When connected with  the recent version of Kodi, I could see only 12 courses are listed in the page. Actually I have more number of courses in Udemy.

Is this something by design?

**Comment by mariuszewski** [comment]
Do you already have a solution ??

**Comment by lwille** [comment]
If you're looking for a solution, try modifying https://github.com/lwille/plugin.video.udemy/blob/master/addon.py#L134 to include a `page_size` parameter.
A smarter solution would be to pass a `page=1` parameter and increment that number until no more items are returned by the API.

Unfortunately the `/api-2.0/users/me/subscribed-courses` API is undocumented, but I assume it has the same pagination pattern. Have a look over here: https://www.udemy.com/developers/methods/get-courses-list/

**Comment by lwille** [comment]
Turns out the API returns a `next` key for every page as long as there are more items, which made it really easy to load all courses.

I'm not sure if this is cool or we'd rather have a proper pagination - users usually don't have classes in the 10s of thousands, so loading them all at once should be fine.

Let me know if it works for you @Purus and @mariuszewski

**Comment by mariuszewski** [comment]
it works great ! thanx !!
